package pt.tecnico.Server;

/* these imported classes are generated by the hello-world-server contract */
import pt.tecnico.grpc.ClientServer;
import pt.tecnico.grpc.ClientToServerServiceGrpc;

import io.grpc.stub.StreamObserver;

public class ClientServerServiceImpl extends ClientToServerServiceGrpc.ClientToServerServiceImplBase {

	@Override
	public void greeting(ClientServer.HelloRequest request, StreamObserver<ClientServer.HelloResponse> responseObserver) {

		// HelloRequest has auto-generated toString method that shows its contents
		System.out.println(request);

		// You must use a builder to construct a new Protobuffer object
		ClientServer.HelloResponse response = ClientServer.HelloResponse.newBuilder()
				.setGreeting("Hello " + request.getName()).build();

		// Use responseObserver to send a single response back
		responseObserver.onNext(response);

		// When you are done, you must call onCompleted
		responseObserver.onCompleted();
	}

	@Override
	public void writeFile(ClientServer.WriteFileRequest request, StreamObserver<ClientServer.WriteFileResponse> responseObserver) {
		System.out.println(request.getFileName());
		System.out.println(request.getFile().toStringUtf8());

		ClientServer.WriteFileResponse response = ClientServer.WriteFileResponse.newBuilder()
		.setAck("Confirmed write of file " + request.getFileName())
		.build();

		// Use responseObserver to send a single response back
		responseObserver.onNext(response);

		// When you are done, you must call onCompleted
		responseObserver.onCompleted();
	}
}
